server:
  hostname: "shiny.dide.ic.ac.uk"
  email: "r.fitzjohn@imperial.ac.uk"
  port_http: 80
  port_https: 443
  port_admin: 9000
  # used for the self-signed certificate
  country: UK
  state: London
  organisation: DIDE

vault:
  address: "https://vault.dide.ic.ac.uk:8200"
  root: "/secret/shiny.dide"

apps:
  msc-idm-2019:
    type: github
    spec: mrc-ide/msc-idm-2019
    admin:
      - rich

  msc-idm-2020:
    type: github
    spec: mrc-ide/msc-idm-2020
    admin:
      - rich

  msc-idm-2021:
    type: github
    spec: mrc-ide/msc-idm-2021@main
    admin:
      - rich

  msc-idm-2022:
    type: github
    spec: mrc-ide/msc-idm-2022@main
    admin:
      - rich

  pfizer-flu-fitting:
    type: github
    spec: mrc-ide/msc-idm-2020/flu
    admin:
      - rich

  infectiousdiseasemodels-2019:
    type: github
    spec: mrc-ide/infectiousdiseasemodels-2019
    admin:
      - rich

  infectiousdiseasemodels-2021:
    type: github
    spec: mrc-ide/infectiousdiseasemodels-2021
    admin:
      - rich

  infectiousdiseasemodels-2022:
    type: github
    spec: mrc-ide/infectiousdiseasemodels-2022
    admin:
      - rich

  infectiousdiseasemodels-brazil:
    type: github
    spec: mrc-ide/infectiousdiseasemodels-brazil@main
    admin:
      - rich

  infectiousdiseasemodels-singapore:
    type: github
    spec: mrc-ide/infectiousdiseasemodels-singapore@master
    admin:
      - rich

  malawi-idm-2022:
    type: github
    spec: mrc-ide/malawi-idm-2022@main
    admin:
      - rich

  infectiousdiseasemodels-lusaka-2022:
    type: github
    spec: mrc-ide/infectiousdiseasemodels-lusaka-2022@main
    admin:
      - rich

  odin:
    type: github
    spec: mrc-ide/odin-app@main
    admin:
      - rich

  eppasmviewer:
    type: github
    spec: mrc-ide/eppasmviewer/inst/shiny/eppasmviewer
    auth:
      type: deploy_key
    groups:
      - admin
      - epidem
    admin:
      - jeff

  polici:
    type: github
    spec: arranhamlet/POLICI

  seasonal_hrp2:
    type: github
    spec: ojwatson/hrp2malaRia/inst/shiny-seasonality/app
    admin: ojwatson

  nimue-national-fits:
    type: github
    spec: mrc-ide/nimue/inst/shiny-nimue-fits/app
    admin: ojwatson

  pfhrp23-explainer:
    type: github
    spec: rjzupkoii/WHO-Malaria-pfhrp23/R@mrc-ide-shiny-deploy
    admin: 
      - ojwatson

  chainchecker:
    type: github
    spec: imperialebola2018/chainchecker
    auth:
      type: deploy_key
    admin:
      - kgaythorpe

  raptor:
    type: github
    spec: mrc-ide/RAPTOR
    auth:
      type: deploy_key
    admin:
      - kgaythorpe
      - arranhamlet

  raptorx:
    type: github
    spec: mrc-ide/RAPTORX
    auth:
      type: deploy_key
    admin:
      - kgaythorpe
      - arranhamlet

  learnr-test:
    type: github
    spec: mrc-ide/learnr_test@main
    admin:
      - rich

  kpcascade:
    type: github
    spec: osymandius/kpcascade
    admin:
      - ostevens

  csavr_mortality:
    type: github
    spec: mrc-ide/csavr-mortality
    admin:
      - ostevens

  naomi-viewer:
    type: github
    spec: mrc-ide/shinyrob
    admin:
      - ostevens

  kp-data:
    type: github
    spec: mrc-ide/kp-data-shiny@main
    admin:
      - ostevens

  hello:
    type: local
    spec: hello

  test:
    type: local
    spec: test
    groups:
      - dide-internal

  shiny90:
    type: github
    spec: mrc-ide/shiny90
    admin:
      - alex

  shiny90-staging:
    type: github
    spec: mrc-ide/shiny90
    admin:
      - alex

  mint:
    type: github
    spec: mrc-ide/shiny-malaria-UI
    admin: ellie
    auth:
      type: deploy_key

  epiestim:
    type: github
    spec: jstockwin/EpiEstimApp/inst/app@release
    admin: acori

  aims-epi-cameroon:
    type: github
    spec: EllieSherrardSmith/AIMS_Cameroon
    admin: ellie
    auth:
      type: deploy_key

  india_covid_model:
      type: github
      spec: ncov-ic/india_covid_model
      admin: verg
      auth:
        type: deploy_key
      groups:
      - india_covid

  s614LineagesUK:
    type: github
    spec: robj411/lineageApp
    admin: rj411

  covid19-forecasts-shiny:
    type: github
    spec: mrc-ide/covid19-forecasts-orderly-shiny@main
    admin: sbhatia

  covid19-orphans:
    type: github
    spec: ImperialCollegeLondon/covid19orphans_shiny@main
    admin: ettieunwin
    auth:
      type: deploy_key
    groups:
    - orphans

  covid19-si-shiny:
    type: github
    spec: mrc-ide/covid19-si-shiny@main
    admin: sbhatia

  tfpbrowser:
    type: github
    spec: mrc-ide/tfpbrowser/inst/app@main
    admin: emvolz
    groups:
      tfpbrowser

  DRpower-app:
    type: github
    spec: shaziaruybal/DRpower_app@main
    admin: shaziaruybal

  starmeds-budget-tool:
    type: github
    spec: mrc-ide/starmeds@main
    admin: adriangh3orghe
    
groups:
  dide-internal:
    - rich
    - jeff
    - acori
  epidem:
    - epidem
    - jeff
  admin:
    - rich
  india_covid:
    - verg
  orphans:
    - ettieunwin
    - covidorphans
  tfpbrowser:
    - tfpbrowser
